name: Reset schedule

on:
  schedule:
    - cron: '0 7 * * 0' # 매주 일요일 16시

jobs:
  reset-schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: pnpm install
      - name: Reset schedule
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: npx ts-node scripts/reset-schedule.ts
